import type { Knex } from 'knex';
import { v4 as uuidv4 } from 'uuid';
import * as bcrypt from 'bcrypt';

export async function seed(knex: Knex): Promise<void> {
  const senhaHash = await bcrypt.hash('Senha@123', 10);
  const UUID_CONDOMINIO = await knex('condominios')
    .select('uuid')
    .first()
    .then((row) => row?.uuid);
  await knex('usuarios').insert([
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ABILIO SILVA MOURAO NETO',
      rg: '155119',
      cpf_cnpj: '21677654287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANA CAROLINA DE ANDRADE LABATE CLEMENTINO DA ROCHA SANTOS',
      rg: '10116311',
      cpf_cnpj: '27527580810',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA NILZA DA SILVA',
      rg: '336473',
      cpf_cnpj: '00059281251',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUCAS ROBERTO DE SOUZA ROCHA',
      rg: '103.108-19',
      cpf_cnpj: '00072538260',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PEDRO PAULO DE SOUZA ROCHA',
      rg: '103.106-06',
      cpf_cnpj: '00072539232',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LIVIA MARIA FIRMINO LEITE',
      rg: '38.488-56',
      cpf_cnpj: '00122474139',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'TAILANA NASCIMENTO DE SOUZA',
      rg: '253.433-94',
      cpf_cnpj: '00148263216',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA JOSE MACHADO DE PAULO',
      rg: '187005',
      cpf_cnpj: '00193877252',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SIMONE APARECIDA LEAL BUSO MAIA',
      rg: '13.876-67',
      cpf_cnpj: '00207297150',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCA CLEICIANE SANTOS SOUZA',
      rg: '108.951-32',
      cpf_cnpj: '00240706293',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JULIO CESAR MELENO DOS REIS FILHO',
      rg: '108.874-07',
      cpf_cnpj: '00262939274',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCIANE VIEIRA MARINHO',
      rg: '109.112-51',
      cpf_cnpj: '00337656266',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PAULO ANTONIO BERNARDINO REZENDE',
      rg: '101.524-90',
      cpf_cnpj: '00343432293',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KELVIN SILVA DE ARAUJO GUSMÃO',
      rg: '12.190.484-69',
      cpf_cnpj: '00397572263',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SOLINO DE MATOS NETO',
      rg: '308517',
      cpf_cnpj: '00399673288',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'BENNY PINHEIRO CUNHA LOPES',
      rg: '004.073-83',
      cpf_cnpj: '00407383224',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RAFAELA FEITOSA ANSELMI',
      rg: '102.110-20',
      cpf_cnpj: '00408666293',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'YAN DENE TUSSOLINI',
      rg: '50.972-61',
      cpf_cnpj: '00442560273',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PEDRO HENRIQUE RESENDE TEIXEIRA CAMPOS',
      rg: '92.900-52',
      cpf_cnpj: '00499974166',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA EDUARDA LEITE DE SOUZA',
      rg: '121.986-33',
      cpf_cnpj: '00586407200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NAYLINE AMARAL GADELHA',
      rg: '47.326-58',
      cpf_cnpj: '00594247101',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RAFAEL BRAGA DE MELO',
      rg: '103.263-13',
      cpf_cnpj: '00686344267',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GABRIELA CORDEIRO CARVALHO CORREIA',
      rg: '101.921-07',
      cpf_cnpj: '00690233280',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FLAVIA LIMA DE OLIVEIRA',
      rg: '102.946-19',
      cpf_cnpj: '00714189200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ESTEFANI DELFINO RODRIGUES',
      rg: '110.893-18',
      cpf_cnpj: '00721405266',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JAQUELINE DURCO PAÇO',
      rg: '065.977-40',
      cpf_cnpj: '00755171756',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'HUGO NOGUEIRA REGO RODRIGUES',
      rg: '134.442-04',
      cpf_cnpj: '00759506264',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'HILDO REGO RODRIGUES JÚNIOR',
      rg: '13.442-12',
      cpf_cnpj: '00759509280',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RENATA NOGUEIRA COLAÇO PIRES',
      rg: '16.474-87',
      cpf_cnpj: '00761824448',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUMA ANDRE MAIA LAMEIRA',
      rg: '107.672-15',
      cpf_cnpj: '00774119276',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ACSON VIEIRA DE SOUZA',
      rg: '12.190.483-02',
      cpf_cnpj: '00779309243',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANDRÉ LUIS QUEIROZ DA SILVA',
      rg: '111.637-39',
      cpf_cnpj: '00785412204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DANILLO SILVA DE LIMA',
      rg: '111.144-87',
      cpf_cnpj: '00798923296',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GRAZIELE EUFRAZIO CORREIA LIMA',
      rg: '10.951-23',
      cpf_cnpj: '00824787242',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIANA BATALHA MACHADO',
      rg: '101.776-71',
      cpf_cnpj: '00848356217',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MATHEUS DA SILVA FREITAS',
      rg: '117.508-20',
      cpf_cnpj: '00855808217',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ENNEDE MOREIRA HERCULANO',
      rg: '118.510-23',
      cpf_cnpj: '00867955201',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MATHEUS MACHADO CUNHA',
      rg: '107.937-47',
      cpf_cnpj: '00878565221',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KEVIA AUGOSTINHO DOS SANTOS MARTINS',
      rg: '111.664-87',
      cpf_cnpj: '00886361273',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JACKELINE SILVA PAZ',
      rg: '103.180-20',
      cpf_cnpj: '00908361203',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NATHALIA BEDIN FERREIRA',
      rg: '128.357-22',
      cpf_cnpj: '00913741205',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSE BRUNO DE MOURA RIPARDO',
      rg: '111.788-17',
      cpf_cnpj: '00915546248',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NICOLE DE CASTRO CORDEIRO BARBOSA',
      rg: '103.928-58',
      cpf_cnpj: '00927427265',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GABRIELA DE CASTRO CORDEIRO BARBOSA',
      rg: '111.902-30',
      cpf_cnpj: '00927428237',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GREICIANE COELHO CAMARGO',
      rg: '777401',
      cpf_cnpj: '01006683135',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANA CRISTINA TEIXEIRA DE SOUZA',
      rg: '077.190.728-21',
      cpf_cnpj: '01007369205',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSIANY FERREIRA DA SILVA FIGUEIREDO',
      rg: '113.809-42',
      cpf_cnpj: '01043572236',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EDER DE OLIVEIRA SANTOS MAEDA',
      rg: '57.672-22',
      cpf_cnpj: '01056213663',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GUSTAVO DE CASTRO VIEIRA',
      rg: '82.996-53',
      cpf_cnpj: '01121180116',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA CAROLINE GOMES DE PAIVA FARIAS',
      rg: '18.530-31',
      cpf_cnpj: '01138372437',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA CERES AFONSO DA SILVA',
      rg: '24116',
      cpf_cnpj: '01148613234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCO TELLES NETTO',
      rg: '306397',
      cpf_cnpj: '01178172953',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA CARINA DA SILVA PAIVA',
      rg: '072.903.917-70',
      cpf_cnpj: '01290247242',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA DE FATIMA DO NASCIMENTO SOUZA',
      rg: '114.124-10',
      cpf_cnpj: '01301949213',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANA LUÍSA DE MOURA PEREIRA',
      rg: '112.770-33',
      cpf_cnpj: '01316678237',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MONICA PAELO',
      rg: '127.366-27',
      cpf_cnpj: '01332086136',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARLOS OLIVEIRA PORTO',
      rg: '106.004-51',
      cpf_cnpj: '01355365619',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ADAILTON DA SILVA E SOUZA',
      rg: '169.277-61',
      cpf_cnpj: '01375764128',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PATRICIA THAIS DELILO',
      rg: '432755',
      cpf_cnpj: '01432840290',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FERNANDA DO NASCIMENTO ANDRADE',
      rg: '464879',
      cpf_cnpj: '01544833202',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RAIZA GALDINO DE SOUZA MELO',
      rg: '10.117.875-2',
      cpf_cnpj: '01579300251',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'TAYLA MACIELE BARROS PONTES',
      rg: '107.429-56',
      cpf_cnpj: '01671494237',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PRISCILA COSTA DE FARIAS',
      cpf_cnpj: '01686930461',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NATHALIA SABOIA DE SOUZA',
      rg: '129.351-82',
      cpf_cnpj: '01728191211',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LETICIA SOUZA SCATOLÃO',
      cpf_cnpj: '01751977170',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GIULIA VICTORIA',
      rg: '127.907-70',
      cpf_cnpj: '01755911211',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CAZE MINUANO LABATE SANTOS',
      rg: '018.192.562-19',
      cpf_cnpj: '01819256219',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'REBECCA HEIDRICH THOEN RIBEIRO',
      rg: '60.698.500-1',
      cpf_cnpj: '01842920090',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOÃO PAULO ALVES MOURA LEITE',
      rg: '106.553-95',
      cpf_cnpj: '01891621203',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'AMANDA CRISTINE DA SILVA ARAÚJO',
      rg: '113.849-99',
      cpf_cnpj: '01909402206',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GABRIELA MONTE LIMA',
      cpf_cnpj: '01924949296',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'THAIS FRARI VIANA',
      rg: '109.099-90',
      cpf_cnpj: '01944731202',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'WALESCKA MACHADO MARTINS',
      rg: '103.169-22',
      cpf_cnpj: '02026858292',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DOUGLAS JONATHAN SANTIAGO FILHO',
      rg: '120.372-90',
      cpf_cnpj: '02040001220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIAH CASTRO',
      rg: '124.923-45',
      cpf_cnpj: '02106834225',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PAULA RAIANE SILVA MACEDO',
      rg: '117.894-09',
      cpf_cnpj: '02122097280',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MIKELE RUTE ALVES NOBR',
      rg: '135.999-41',
      cpf_cnpj: '02127778235',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VANESSA URQUIOLA DO NASCIMENTO',
      rg: '021.330.390-66',
      cpf_cnpj: '02133039066',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DILERMANDO NOVAIS RODRIGUES',
      rg: '113.594-39',
      cpf_cnpj: '02172353280',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RICARDO NELSON FABIAN AMARILHA DE MANTILHA',
      rg: '315.004-86',
      cpf_cnpj: '02250005982',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUAN DA SILVA ARAÚJO',
      rg: '116.923-32',
      cpf_cnpj: '02311002210',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VANESSA YASMIN GOMES DE LIMA',
      rg: '118.517-59',
      cpf_cnpj: '02335919237',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'BRUNA EMANUELLE FERNANDES LOPES',
      rg: '118.877-96',
      cpf_cnpj: '02390594255',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ADLER BELARMINO DO NASCIMENTO',
      rg: '12.140.457-59',
      cpf_cnpj: '02392416222',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PEDRO HENRIQUE VILHAMOR GOMES',
      rg: '137.118-14',
      cpf_cnpj: '02435362242',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA FERNANDA LABATE SANTOS',
      rg: '024.401.892-86',
      cpf_cnpj: '02440189286',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANDERSON MUNIZ DO NASCIMENTO',
      rg: '116.886-02',
      cpf_cnpj: '02476461210',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'HISSYS BEATRIZ BORGES LOPES PESSOA',
      rg: '105.692-27',
      cpf_cnpj: '02487386231',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'AURELIO REZENDE CAMPOS ROSA',
      rg: '50.151-01',
      cpf_cnpj: '02492251152',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSE AUGUSTO RODRIGUES FERREIRA',
      rg: '31396',
      cpf_cnpj: '02498170200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NICKOLE LIMA MESQUITA',
      rg: '125.275-56',
      cpf_cnpj: '02507496290',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NICKOLAS WALLACE LIMA MESQUITA',
      rg: '125.268-43',
      cpf_cnpj: '02507504226',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LIDIANE DOS SANTOS SILVA',
      cpf_cnpj: '02510512269',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ESTER ROCHA DE ARAÚJO',
      cpf_cnpj: '02540340202',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GILSON DE ABREU MELO',
      rg: '058503',
      cpf_cnpj: '02591812268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSE LUCAS DE CASTRO AQUINO',
      rg: '110.231-98',
      cpf_cnpj: '02592880208',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VERÔNICA OLIVEIRA ABUGOCHE',
      rg: '42229',
      cpf_cnpj: '02605376249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LEANDRA NOVAIS BATISTA',
      rg: '107.836-10',
      cpf_cnpj: '02618335295',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EMANUELLI NOVAIS DA SILVA CASTRO',
      rg: '120.410-17',
      cpf_cnpj: '02626865206',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LEONARDO DE HOLANDA VASCONCELOS',
      rg: '118.437-56',
      cpf_cnpj: '02681603250',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALLAN HENRIQUE DE ARAÚJO NOGUEIRA',
      rg: '127.606-09',
      cpf_cnpj: '02702815251',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RÉGIA BELTRÃO TEIXEIRA BEZERRA',
      rg: '970.023.722-42',
      cpf_cnpj: '02738364390',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSÉ ORNY NOGUEIRA JUCA',
      rg: '44810',
      cpf_cnpj: '02834774234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LEONARDO MESQUITA ALBUQUERQUE',
      rg: '122.047-73',
      cpf_cnpj: '02870078200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUCAS MESQUITA ALBUQUERQUE',
      rg: '122.030-76',
      cpf_cnpj: '02870093276',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VALDECI SOLINGE DE FARIAS',
      rg: '244606',
      cpf_cnpj: '02886812234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANDRESSA SILVA DOS SANTOS',
      cpf_cnpj: '02891165209',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JANAINA FERRARI LONGUINI',
      rg: '303444',
      cpf_cnpj: '02942055944',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA CLARA FERREIRA DOS SANTOS COSTA',
      rg: '250.436-48',
      cpf_cnpj: '03068815274',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MIGUEL FERREIRA DOS SANTOS COSTA',
      cpf_cnpj: '03068881226',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'INGRID NATASCHA DE SOUZA SAMPAIO',
      rg: '115.266-53',
      cpf_cnpj: '03123469212',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MATHEUS DUTRA RAMOS BRANA',
      rg: '111.613-10',
      cpf_cnpj: '03128224218',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ODAIR SCHARNOWSKI',
      rg: '37.196-60',
      cpf_cnpj: '03150001986',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FABIO ALEXANDRE COSTA DE FARIAS',
      rg: '25.068-26',
      cpf_cnpj: '03150945402',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ISNA FERNANDA MOREIRA DE OLIVEIRA',
      rg: '123.471-67',
      cpf_cnpj: '03161330277',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'YASMIN LOUISE ROCHA JUCÁ',
      rg: '123.742-45',
      cpf_cnpj: '03185316231',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'HENRIQUE OLIVEIRA SCATOLIN',
      rg: '032.712.812-70',
      cpf_cnpj: '03271281270',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARCIO DOS SANTOS ROMUALDO',
      rg: '09.907.245-6',
      cpf_cnpj: '03306806765',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANDERSON LUIZ PINTRO',
      rg: '40.057-16',
      cpf_cnpj: '03315406901',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NEILSON DE SOUZA DA COSTA',
      rg: '139.690-44',
      cpf_cnpj: '03395194604',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GABRIELA SILVA GOTI',
      rg: '124.876-19',
      cpf_cnpj: '03406850260',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOÃO FERNANDO DO NASCIMENTO SOARES',
      rg: '102.110-39',
      cpf_cnpj: '03419064250',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALINE AUGUSTO FERNANDES',
      rg: '204.064-52',
      cpf_cnpj: '03453798104',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SOFIA ROCHA PIRES BARBOZA',
      rg: '125.456-86',
      cpf_cnpj: '03486490290',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LAURA REBOUÇAS DALACOSTA',
      rg: '124.590-20',
      cpf_cnpj: '03533151255',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KAROLAYNE NASCIMENTO DE QUEIROZ',
      rg: '119.723-00',
      cpf_cnpj: '03560883245',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA LUZIA NUNES DOS SANTOS',
      rg: '27304',
      cpf_cnpj: '03582353249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CAMILO MENDES DE OLIVEIRA',
      rg: '47.041.612-9',
      cpf_cnpj: '03586321961',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CATARINA MARINHO VILELA',
      rg: '128.238-30',
      cpf_cnpj: '03588111204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUIZ FELIPE NOGUEIRA VERAS',
      rg: '126.449-86',
      cpf_cnpj: '03629794211',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCO ANTONIO VIEIRA BRANA',
      rg: '02.395-46',
      cpf_cnpj: '03690563234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARCELO ANUTE BADER RIBEIRO',
      cpf_cnpj: '03726325212',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUCAS FREITAS PASSOS',
      cpf_cnpj: '03727385243',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ELMO CARDOSO DOS SANTOS',
      rg: '58426',
      cpf_cnpj: '03762033234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ELMIRA OLIVEIRA DE FARIAS',
      rg: '00.456-79',
      cpf_cnpj: '03775259287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'QUETULEN FIGUEIREDO MELO',
      rg: '038.406.922-37',
      cpf_cnpj: '03840692237',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUIS FERNANDO FELTRINI PAES LEME',
      rg: '128.919-40',
      cpf_cnpj: '03857563214',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DAVI ALBUQUERQUE RODRIGUES LIMA',
      rg: '134.125-31',
      cpf_cnpj: '03880987246',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GIOVANA LIMA DE SOUZA',
      rg: '127.953-99',
      cpf_cnpj: '03883038245',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA LUIZA NOVAIS',
      rg: '013167',
      cpf_cnpj: '03900627231',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ISADORA TAVARES ALENCAR DA SILVA',
      rg: '128.042-40',
      cpf_cnpj: '03901538267',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'THIAGO DUTRA RAMOS BRAÑA',
      rg: '115.372-48',
      cpf_cnpj: '03915354201',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'BIANCA DE SOUZA OLIVEIRA',
      cpf_cnpj: '03971815235',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CAROLINA SCHETTINI VIANA',
      rg: '115.990-30',
      cpf_cnpj: '04062905205',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ABRÃAO ASSIS FELICIO',
      rg: '33113',
      cpf_cnpj: '04065050200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANTONIO FIALHO MARINHO',
      rg: '41223',
      cpf_cnpj: '04065638291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA CLEIDE CORREIA LIMA',
      rg: '599743',
      cpf_cnpj: '04069307249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'TALYSON NASCIMENTO DE MELO',
      rg: '041.087.322-51',
      cpf_cnpj: '04108732251',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'BRUNO RODRIGUES GONÇALVES',
      rg: '118.410-95',
      cpf_cnpj: '04173509294',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PEDRO RAVI RODRIGUES GONÇALVES',
      cpf_cnpj: '04173518285',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LETÍCIA CARVALHO DA MOTA',
      rg: '129.591-89',
      cpf_cnpj: '04189956210',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JORGE JOSE DE MOURA NETO',
      rg: '129.776-16',
      cpf_cnpj: '04215986206',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GIOVANNA CHRISTINE MARQUES FARIA',
      rg: '131.779-66',
      cpf_cnpj: '04219496270',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FERNANDA PAOLA MARQUES FARIA',
      rg: '131.724-33',
      cpf_cnpj: '04219497242',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GUSTAVO FERNANDES RODRIGUES',
      rg: '129.795-46',
      cpf_cnpj: '04221235284',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DANNYELLE CHRISTINNY BEZERRA DE OLIVEIRA FREITAS PASSOS',
      rg: '18.096-74',
      cpf_cnpj: '04380070400',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JACINTO DOMINGOS DE ARAUJO',
      cpf_cnpj: '04388143120',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA MARLIZETE DE MOURA PEREIRA',
      rg: '128115',
      cpf_cnpj: '04485432220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANTONIA LIMA DE ABREU',
      rg: '064316',
      cpf_cnpj: '04569849253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RAIMUNDO NONATO FERREIRA DO NASCIMENTO',
      rg: '50875',
      cpf_cnpj: '04572793204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANITA DIAS MOURA DA SILVA',
      rg: '80039',
      cpf_cnpj: '04578589234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GILSON DORIA DE LUCENA JUNIOR',
      rg: '322898',
      cpf_cnpj: '04611983471',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KAUANNA LUZIA DE ALMEIDA COSTA',
      rg: '74.384-53',
      cpf_cnpj: '04616506221',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CELLE CRISTIANNE MENDES EVANGELISTA BELCHIOR',
      cpf_cnpj: '04641185654',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GUIDO WAGNER VILHAMOR',
      rg: '52319',
      cpf_cnpj: '04882288249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RAFAEL AUGUSTO SATRAPA',
      rg: '82.716-03',
      cpf_cnpj: '04925958607',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'IVAN CHICOSKI',
      rg: '840.741-36',
      cpf_cnpj: '04932379927',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA GABRIELA ESTEVES BEZERRA',
      rg: '19.448-59',
      cpf_cnpj: '05164834200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'THAÍS CRISTINA PINTO DE LIMA',
      rg: '116.678-43',
      cpf_cnpj: '05252370206',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'HEITOR REBOUÇAS DALACOSTA',
      rg: '135.749-14',
      cpf_cnpj: '05292010200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MATEUS DA SILVA RIBEIRO',
      rg: '12.112.764-7',
      cpf_cnpj: '05370088292',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EDER JACOBOSKI VIEGAS',
      rg: '15.456-33',
      cpf_cnpj: '05372282762',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANA BEATRIZ GOMES DE ARAUJO',
      rg: '128.627-46',
      cpf_cnpj: '05389865227',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUIZ EDUARDO GOMES ARAUJO',
      rg: '115.686-15',
      cpf_cnpj: '05389867270',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GEISON JOSÉ DO PRADO VENTURA',
      rg: '49.571.851-8',
      cpf_cnpj: '05470465101',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KELLYN APARECIDA DIHEL',
      rg: '13.587-72',
      cpf_cnpj: '05506763255',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SERGIO PAULO DE FREITAS MARTINS JUNIOR',
      rg: '108.437-58',
      cpf_cnpj: '05535300624',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA LUCHESE GIULIANI',
      rg: '12.347.467-9',
      cpf_cnpj: '05608153286',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VINICIUS SOSTER DE LIIMA',
      rg: '22.222-22',
      cpf_cnpj: '05663117202',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VITOR GABRIEL BRAGA RIBEIRO',
      rg: '122.015-29',
      cpf_cnpj: '05865542206',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSE VICTOR DOS SANTOS',
      rg: '52787',
      cpf_cnpj: '05872480253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NANCI APARECIDA CASELLATO ROSALEM',
      rg: '450.105-72',
      cpf_cnpj: '05982561800',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EMMANOEL PORFIRIO NEVES FILHO',
      rg: '28.197-14',
      cpf_cnpj: '06071931401',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GYOVANNA GOMES SIMÃO DE OLIVEIRA',
      rg: '121.000-48',
      cpf_cnpj: '06179281262',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'THIAGO HEITOR FERREIRA COSTA',
      rg: '135.146-71',
      cpf_cnpj: '06199303652',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOÃO PAULO MACHADO',
      rg: '11.277.071-16',
      cpf_cnpj: '06236617562',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANTHONY LEAL BUSO MAIA',
      rg: '134.883-68',
      cpf_cnpj: '06435733210',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANGELA MARIA MAGALHÃES',
      rg: '103.968-21',
      cpf_cnpj: '06567161698',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PEDRO AUGUSTO FRANÇA DE MACEDO',
      rg: '119.275-90',
      cpf_cnpj: '06645559690',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RAIMUNDO MENANDRO DE SOUZA',
      cpf_cnpj: '06710395472',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANNA CLARA ANDRADE RODRIGUES',
      rg: '108.012-19',
      cpf_cnpj: '06892097200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CARLOS RODRIGO COSTA DE ARAUJO',
      rg: '118.142-25',
      cpf_cnpj: '07051512200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RENATA LUCIA CARDOSO GOMES DE OLIVEIRA',
      rg: '3379',
      cpf_cnpj: '07110796760',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KELTON PAULINO ARAUJO DE SOUZA',
      rg: '132.338-58',
      cpf_cnpj: '07209489240',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCO PAULINO DE SOUZA JUNIOR',
      cpf_cnpj: '07209499202',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RONEI GOMES DE OLIVEIRA',
      rg: '01.137.312-4',
      cpf_cnpj: '07290671732',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PAULA CAMAROTA DOMITH DE LUCENA',
      rg: '130.062-66',
      cpf_cnpj: '07337685637',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KATUYUKI YOMURA',
      rg: '308.007-54',
      cpf_cnpj: '07474610825',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALESSANDRA CORREIA DOS SANTOS',
      rg: '137.646-59',
      cpf_cnpj: '07548375646',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JÉSSICA FEITOSA',
      rg: '30.911-56',
      cpf_cnpj: '07564745401',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'THALLES FERREIRA COSTA',
      rg: '115.299-94',
      cpf_cnpj: '07730321696',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DANIELE DE SOUZA C. ROMUALDO',
      rg: '419350',
      cpf_cnpj: '07738766711',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUIZ FERNANDO DUARTE MAIA',
      rg: '061586',
      cpf_cnpj: '07867638253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SOLINO DE MATOS FILHOS',
      rg: '75529',
      cpf_cnpj: '07882980200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CAÍQUE CIRANO DI PAULA',
      rg: '310.900-10',
      cpf_cnpj: '07902545490',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FILOGONIO CASSIANO RIBEIRO',
      rg: '35019',
      cpf_cnpj: '07911769249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOÃO LIMA DE SOUZA',
      rg: '57536',
      cpf_cnpj: '07914784249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'AMIRA VIRGILIA DA COSTA PESCADOR',
      rg: '065781',
      cpf_cnpj: '07923819204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARCELO ANGELI ROZA',
      rg: '69918',
      cpf_cnpj: '08111151780',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUCAS SQUERSATO',
      rg: '52.397-42',
      cpf_cnpj: '08139653900',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FELIPE MARTINI BELCHIOR',
      rg: '133.036-27',
      cpf_cnpj: '08146244726',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DRAULT SANTA CRUZ DE ALMEIDA NETO',
      rg: '33.147-34',
      cpf_cnpj: '08242175438',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'AVILA VITÓRIA ARAUJO DE PAIVA',
      rg: '095285',
      cpf_cnpj: '08278767262',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MILENA NOVAK AGGIO',
      rg: '11.082.554-4',
      cpf_cnpj: '08440019963',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JADSON RAGO',
      rg: '129.919-10',
      cpf_cnpj: '08525501468',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EDIMIR RODRIGUES DOS SANTOS',
      rg: '08.186-89',
      cpf_cnpj: '09144749287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA CLARA BACELAR FREITAS',
      cpf_cnpj: '09267731190',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOÃO MANOEL BACELAR FREITAS',
      rg: '070987',
      cpf_cnpj: '09267758128',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOÃO RIBEIRO DO NASCIMENTO',
      rg: '083213',
      cpf_cnpj: '09570608234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MICHEL MACEDO DE MATTOS',
      rg: '382205',
      cpf_cnpj: '10013179713',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'HELLEN DA SILVA SOUZA OLIVEIRA ROZA',
      rg: '127.320-60',
      cpf_cnpj: '10144199726',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ZELIA MARIA DE SOUZA CUNHA',
      rg: '10.213.331-74',
      cpf_cnpj: '10213331748',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANA PAULA SOUZA DE OLIVEIRA',
      rg: '102.373.762-02',
      cpf_cnpj: '10237376202',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCO DJALMA DA SILVA',
      rg: '189317',
      cpf_cnpj: '10645225487',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GABRIELY SOUZA OLIVEIRA',
      rg: '107.737.692-85',
      cpf_cnpj: '10773769285',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NARCISO CARLOS SARAIVA CESAR',
      cpf_cnpj: '10849048885',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCA DAS XAGAS OLIVEIRA DA CONCEIÇÃO',
      rg: '040613',
      cpf_cnpj: '11273046234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ERICO MAURICIO PIRES BARBOZA',
      rg: '26.894.172-5',
      cpf_cnpj: '11323867805',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIANA COLODETTI',
      rg: '21.020-69',
      cpf_cnpj: '11339797771',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JULIANO GREGOLIS',
      rg: '247.614-80',
      cpf_cnpj: '11745902899',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'IVANETE CARLOS NASCIMENTO',
      rg: '174296',
      cpf_cnpj: '12893358268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'BENIDITA CUNHA DO NASCIMENTO',
      rg: '131087',
      cpf_cnpj: '12952427291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EDILENA LEITE ORTEGA GONZALEZ',
      rg: '051.490-45',
      cpf_cnpj: '13059173249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ROMEU CORDEIRO BARBOSA FILHO',
      rg: '102214',
      cpf_cnpj: '13338390220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ROMARIO DIVINO FARIA',
      rg: '22.664.736-5',
      cpf_cnpj: '13463286840',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCO AFONSO GONÇALVES DE FREITAS',
      rg: '102659',
      cpf_cnpj: '13814486234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ARACELE MARIA BARROSO DE MACEDO',
      rg: '119911',
      cpf_cnpj: '13865072291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCA DALACOSTA',
      rg: '162816',
      cpf_cnpj: '13917676249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA VITÓRIA MAGALHAES BARBOSA',
      rg: '204.277-32',
      cpf_cnpj: '13965668641',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ROGERIO HENRIQUES NETTO',
      rg: '15.721.797-8',
      cpf_cnpj: '14457145823',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RAFAEL LEITE GREGOLIS',
      rg: '135.886-48',
      cpf_cnpj: '14725722626',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'AMADO DA SILVA',
      rg: '118.044-91',
      cpf_cnpj: '16127145953',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCIS KASHIMA',
      rg: '16.546.506-2',
      cpf_cnpj: '16871547835',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ISO VIEIRA DA SILVA',
      rg: '11.333-42',
      cpf_cnpj: '17025818615',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'IRACEMA KAOR UEHARA YOMURA',
      rg: '439.201-35',
      cpf_cnpj: '17682934816',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARCUS VINICIUS SHOITI YOMURA',
      rg: '22.901.104-4',
      cpf_cnpj: '17682937831',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'TULIO VILLELA LEMOS BAPTISTA DA COSTA',
      rg: '19.789.827-0',
      cpf_cnpj: '17820479809',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCO ALBERTO GONÇALVES DE FREITAS',
      rg: '161522',
      cpf_cnpj: '18140734268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JULIO CESAR MORAES NANTES',
      rg: '675133',
      cpf_cnpj: '18155804100',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'COSME DE SOUZA LEITE',
      rg: '141423',
      cpf_cnpj: '18297846253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JANETE DA COSTA FRANÇA',
      rg: '12.300-17',
      cpf_cnpj: '18315003291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSEMIR BASTOS CANIZO',
      rg: '116828',
      cpf_cnpj: '18322042272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUIS PEDRO DE MELO PLESE',
      rg: '24.724.374-7',
      cpf_cnpj: '18440549857',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSE ALBERTO ELISIARIO DE MACEDO',
      rg: '16.691-19',
      cpf_cnpj: '18804225653',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCO PAULINO DE SOUZA',
      rg: '162565',
      cpf_cnpj: '19602286253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ISLENE MARIA TORRES AMARAL',
      rg: '196.074-40',
      cpf_cnpj: '19607440200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ROSANGELA DA SILVA FREITAS',
      rg: '153984',
      cpf_cnpj: '19628676253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ELIANY NAZIRA DA ROCHA MANSOUR DO VALLE',
      rg: '149404',
      cpf_cnpj: '19649592253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA SONIA DANTAS ALVES',
      rg: '106317',
      cpf_cnpj: '19655681220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALDENORA DE CASTRO CORDEIRO',
      rg: '223274',
      cpf_cnpj: '19712405249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA DO SOCORRO DE OLIVEIRA FERRERIRA',
      rg: '88964',
      cpf_cnpj: '19718756272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA DE FATIMA RIBEIRO DE LIMA',
      rg: '146271',
      cpf_cnpj: '19721196215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DENISE GONÇALVES VIEIRA',
      rg: '088940',
      cpf_cnpj: '19742274215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RODRIGO MINUANO CLEMENTINO DA ROCHA SANTOS',
      rg: '19.522.623-5',
      cpf_cnpj: '20454335873',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CELSO JERONIMO DE SOUZA',
      rg: '19.681-86',
      cpf_cnpj: '21500061972',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ROBERTO MONTEIRO DA ROCHA FILHO',
      rg: '137772',
      cpf_cnpj: '21578761204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALCINEIDE ALMEIDA DE QUEIROZ MATOS',
      rg: '135783',
      cpf_cnpj: '21580316204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CELIA MARIA RODRIGUES KADOR',
      rg: '138124',
      cpf_cnpj: '21595429204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VALDEMIR BARBOSA DOS SANTOS',
      rg: '142391',
      cpf_cnpj: '21597227234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ROSANGELA MARIA CEZINO DA SILVA',
      rg: '143731',
      cpf_cnpj: '21632375249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARCELO VASCONCELOS AQUINO',
      rg: '138522',
      cpf_cnpj: '21633533204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOÃO VALDEMIR SOUZA DE CARVALHO',
      rg: '216.381-44',
      cpf_cnpj: '21638144249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LAUDIVON DE OLIVEIRA NOGUEIRA',
      rg: '138910',
      cpf_cnpj: '21655367234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ERINETE DA CRUZ MACHADO',
      rg: '144137',
      cpf_cnpj: '21659117291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EFRAIN ENRIQUE MENDONZA MENDIVIL FILHO',
      rg: '110324',
      cpf_cnpj: '21712310259',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANTÔNIA DA SILVA SOUZA ROCHA',
      rg: '157304',
      cpf_cnpj: '21732124272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VANUSA MARIA FERREIRA GOMES',
      rg: '149886',
      cpf_cnpj: '21741611253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ELIANE MARA CHAVES VILHAMOR',
      rg: '136098',
      cpf_cnpj: '21754527272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA AUXILIADORA DE OLIVEIRA MARINHO',
      rg: '42.813-26',
      cpf_cnpj: '21778949215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSE DONIZETI AIELO JUNIOR',
      rg: '345.492-03',
      cpf_cnpj: '21778951899',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARION VIRGINIA YUMI YOMURA',
      rg: '22.901.326-0',
      cpf_cnpj: '22382562889',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARJORIE VIVIAN HIKARY YOMURA',
      rg: '22.901.327-2',
      cpf_cnpj: '22382568810',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VANESSA DE SOUZA FELTRINI PAES LEME',
      rg: '355916',
      cpf_cnpj: '22755441860',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DANIELA SOARES DE SOUZA BRAGA',
      rg: '37.553.949-9',
      cpf_cnpj: '22974722857',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
  ]);
}
