export enum TipoNotificacao {
  ENCOMENDA_RECEBIDA = 'ENCOMENDA_RECEBIDA',
  ENCOMENDA_LEMBRETE = 'ENCOMENDA_LEMBRETE',
  ENCOMENDA_ENTREGUE = 'ENCOMENDA_ENTREGUE',
  ALERTA_SISTEMA = 'ALERTA_SISTEMA',
}
