import type { Knex } from 'knex';
import { v4 as uuidv4 } from 'uuid';

export async function seed(knex: Knex): Promise<void> {
  await knex('unidades').del();
  const UUID_CONDOMINIO = await knex('condominios')
    .select('uuid')
    .first()
    .then((row) => row?.uuid);

  await knex('unidades').insert([
    // Quadra 01 (22 unidades)
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0101',
      quadra: '01',
      lote: '01',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0102',
      quadra: '01',
      lote: '02',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0103',
      quadra: '01',
      lote: '03',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0104',
      quadra: '01',
      lote: '04',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0105',
      quadra: '01',
      lote: '05',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0106',
      quadra: '01',
      lote: '06',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0107',
      quadra: '01',
      lote: '07',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0108',
      quadra: '01',
      lote: '08',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0109',
      quadra: '01',
      lote: '09',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0110',
      quadra: '01',
      lote: '10',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0111',
      quadra: '01',
      lote: '11',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0112',
      quadra: '01',
      lote: '12',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0113',
      quadra: '01',
      lote: '13',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0114',
      quadra: '01',
      lote: '14',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0115',
      quadra: '01',
      lote: '15',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0116',
      quadra: '01',
      lote: '16',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0117',
      quadra: '01',
      lote: '17',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0118',
      quadra: '01',
      lote: '18',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0119',
      quadra: '01',
      lote: '19',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0120',
      quadra: '01',
      lote: '20',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0121',
      quadra: '01',
      lote: '21',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0122',
      quadra: '01',
      lote: '22',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },

    // Quadra 02 (31 unidades)
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0201',
      quadra: '02',
      lote: '01',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0202',
      quadra: '02',
      lote: '02',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0203',
      quadra: '02',
      lote: '03',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0204',
      quadra: '02',
      lote: '04',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0205',
      quadra: '02',
      lote: '05',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0206',
      quadra: '02',
      lote: '06',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0207',
      quadra: '02',
      lote: '07',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0208',
      quadra: '02',
      lote: '08',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0209',
      quadra: '02',
      lote: '09',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0210',
      quadra: '02',
      lote: '10',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0211',
      quadra: '02',
      lote: '11',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0212',
      quadra: '02',
      lote: '12',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0213',
      quadra: '02',
      lote: '13',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0214',
      quadra: '02',
      lote: '14',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0215',
      quadra: '02',
      lote: '15',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0216',
      quadra: '02',
      lote: '16',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0217',
      quadra: '02',
      lote: '17',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0218',
      quadra: '02',
      lote: '18',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0219',
      quadra: '02',
      lote: '19',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0220',
      quadra: '02',
      lote: '20',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0221',
      quadra: '02',
      lote: '21',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0222',
      quadra: '02',
      lote: '22',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0223',
      quadra: '02',
      lote: '23',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0224',
      quadra: '02',
      lote: '24',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0225',
      quadra: '02',
      lote: '25',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0226',
      quadra: '02',
      lote: '26',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0227',
      quadra: '02',
      lote: '27',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0228',
      quadra: '02',
      lote: '28',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0229',
      quadra: '02',
      lote: '29',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0230',
      quadra: '02',
      lote: '30',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0231',
      quadra: '02',
      lote: '31',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },

    // Quadra 03 (36 unidades)
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0301',
      quadra: '03',
      lote: '01',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0302',
      quadra: '03',
      lote: '02',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0303',
      quadra: '03',
      lote: '03',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0304',
      quadra: '03',
      lote: '04',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0305',
      quadra: '03',
      lote: '05',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0306',
      quadra: '03',
      lote: '06',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0307',
      quadra: '03',
      lote: '07',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0308',
      quadra: '03',
      lote: '08',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0309',
      quadra: '03',
      lote: '09',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0310',
      quadra: '03',
      lote: '10',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0311',
      quadra: '03',
      lote: '11',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0312',
      quadra: '03',
      lote: '12',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0313',
      quadra: '03',
      lote: '13',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0314',
      quadra: '03',
      lote: '14',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0315',
      quadra: '03',
      lote: '15',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0316',
      quadra: '03',
      lote: '16',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0317',
      quadra: '03',
      lote: '17',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0318',
      quadra: '03',
      lote: '18',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0319',
      quadra: '03',
      lote: '19',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0320',
      quadra: '03',
      lote: '20',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0321',
      quadra: '03',
      lote: '21',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0322',
      quadra: '03',
      lote: '22',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0323',
      quadra: '03',
      lote: '23',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0324',
      quadra: '03',
      lote: '24',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0325',
      quadra: '03',
      lote: '25',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0326',
      quadra: '03',
      lote: '26',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0327',
      quadra: '03',
      lote: '27',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0328',
      quadra: '03',
      lote: '28',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0329',
      quadra: '03',
      lote: '29',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0330',
      quadra: '03',
      lote: '30',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0331',
      quadra: '03',
      lote: '31',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0332',
      quadra: '03',
      lote: '32',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0333',
      quadra: '03',
      lote: '33',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0334',
      quadra: '03',
      lote: '34',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0335',
      quadra: '03',
      lote: '35',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0336',
      quadra: '03',
      lote: '36',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },

    // Quadra 04 (11 unidades)
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0401',
      quadra: '04',
      lote: '01',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0402',
      quadra: '04',
      lote: '02',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0403',
      quadra: '04',
      lote: '03',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0404',
      quadra: '04',
      lote: '04',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0405',
      quadra: '04',
      lote: '05',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0406',
      quadra: '04',
      lote: '06',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0407',
      quadra: '04',
      lote: '07',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0408',
      quadra: '04',
      lote: '08',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0409',
      quadra: '04',
      lote: '09',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0410',
      quadra: '04',
      lote: '10',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0411',
      quadra: '04',
      lote: '11',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },

    // Quadra 05 (15 unidades)
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0501',
      quadra: '05',
      lote: '01',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0502',
      quadra: '05',
      lote: '02',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0503',
      quadra: '05',
      lote: '03',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0504',
      quadra: '05',
      lote: '04',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0505',
      quadra: '05',
      lote: '05',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0506',
      quadra: '05',
      lote: '06',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0507',
      quadra: '05',
      lote: '07',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0508',
      quadra: '05',
      lote: '08',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0509',
      quadra: '05',
      lote: '09',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0510',
      quadra: '05',
      lote: '10',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0511',
      quadra: '05',
      lote: '11',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0512',
      quadra: '05',
      lote: '12',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0513',
      quadra: '05',
      lote: '13',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0514',
      quadra: '05',
      lote: '14',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0515',
      quadra: '05',
      lote: '15',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },

    // Quadra 06 (26 unidades)
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0601',
      quadra: '06',
      lote: '01',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0602',
      quadra: '06',
      lote: '02',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0603',
      quadra: '06',
      lote: '03',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0604',
      quadra: '06',
      lote: '04',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0605',
      quadra: '06',
      lote: '05',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0606',
      quadra: '06',
      lote: '06',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0607',
      quadra: '06',
      lote: '07',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0608',
      quadra: '06',
      lote: '08',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0609',
      quadra: '06',
      lote: '09',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0610',
      quadra: '06',
      lote: '10',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0611',
      quadra: '06',
      lote: '11',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0612',
      quadra: '06',
      lote: '12',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0613',
      quadra: '06',
      lote: '13',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0614',
      quadra: '06',
      lote: '14',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0615',
      quadra: '06',
      lote: '15',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0616',
      quadra: '06',
      lote: '16',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0617',
      quadra: '06',
      lote: '17',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0618',
      quadra: '06',
      lote: '18',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0619',
      quadra: '06',
      lote: '19',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0620',
      quadra: '06',
      lote: '20',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0621',
      quadra: '06',
      lote: '21',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0622',
      quadra: '06',
      lote: '22',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0623',
      quadra: '06',
      lote: '23',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0624',
      quadra: '06',
      lote: '24',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0625',
      quadra: '06',
      lote: '25',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0626',
      quadra: '06',
      lote: '26',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },

    // Quadra 07 (19 unidades)
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0701',
      quadra: '07',
      lote: '01',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0702',
      quadra: '07',
      lote: '02',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0703',
      quadra: '07',
      lote: '03',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0704',
      quadra: '07',
      lote: '04',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0705',
      quadra: '07',
      lote: '05',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0706',
      quadra: '07',
      lote: '06',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0707',
      quadra: '07',
      lote: '07',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0708',
      quadra: '07',
      lote: '08',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0709',
      quadra: '07',
      lote: '09',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0710',
      quadra: '07',
      lote: '10',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0711',
      quadra: '07',
      lote: '11',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0712',
      quadra: '07',
      lote: '12',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0713',
      quadra: '07',
      lote: '13',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0714',
      quadra: '07',
      lote: '14',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0715',
      quadra: '07',
      lote: '15',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0716',
      quadra: '07',
      lote: '16',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0717',
      quadra: '07',
      lote: '17',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0718',
      quadra: '07',
      lote: '18',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0719',
      quadra: '07',
      lote: '19',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },

    // Quadra 08 (18 unidades)
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0801',
      quadra: '08',
      lote: '01',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0802',
      quadra: '08',
      lote: '02',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0803',
      quadra: '08',
      lote: '03',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0804',
      quadra: '08',
      lote: '04',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0805',
      quadra: '08',
      lote: '05',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0806',
      quadra: '08',
      lote: '06',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0807',
      quadra: '08',
      lote: '07',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0808',
      quadra: '08',
      lote: '08',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0809',
      quadra: '08',
      lote: '09',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0810',
      quadra: '08',
      lote: '10',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0811',
      quadra: '08',
      lote: '11',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0812',
      quadra: '08',
      lote: '12',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0813',
      quadra: '08',
      lote: '13',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0814',
      quadra: '08',
      lote: '14',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0815',
      quadra: '08',
      lote: '15',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0816',
      quadra: '08',
      lote: '16',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0817',
      quadra: '08',
      lote: '17',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0818',
      quadra: '08',
      lote: '18',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },

    // Quadra 09 (11 unidades)
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0901',
      quadra: '09',
      lote: '01',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0902',
      quadra: '09',
      lote: '02',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0903',
      quadra: '09',
      lote: '03',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0904',
      quadra: '09',
      lote: '04',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0905',
      quadra: '09',
      lote: '05',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0906',
      quadra: '09',
      lote: '06',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0907',
      quadra: '09',
      lote: '07',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0908',
      quadra: '09',
      lote: '08',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0909',
      quadra: '09',
      lote: '09',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0910',
      quadra: '09',
      lote: '10',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '0911',
      quadra: '09',
      lote: '11',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },

    // Quadra 10 (05 unidades)
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1001',
      quadra: '10',
      lote: '01',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1002',
      quadra: '10',
      lote: '02',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1003',
      quadra: '10',
      lote: '03',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1004',
      quadra: '10',
      lote: '04',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1005',
      quadra: '10',
      lote: '05',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },

    // Quadra 11 (14 unidades)
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1101',
      quadra: '11',
      lote: '01',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1102',
      quadra: '11',
      lote: '02',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1103',
      quadra: '11',
      lote: '03',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1104',
      quadra: '11',
      lote: '04',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1105',
      quadra: '11',
      lote: '05',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1106',
      quadra: '11',
      lote: '06',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1107',
      quadra: '11',
      lote: '07',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1108',
      quadra: '11',
      lote: '08',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1109',
      quadra: '11',
      lote: '09',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1110',
      quadra: '11',
      lote: '10',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1111',
      quadra: '11',
      lote: '11',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1112',
      quadra: '11',
      lote: '12',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1113',
      quadra: '11',
      lote: '13',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      unidade: '1114',
      quadra: '11',
      lote: '14',
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
  ]);
}
