import type { Knex } from 'knex';
import { v4 as uuidv4 } from 'uuid';
import * as bcrypt from 'bcrypt';

export async function seed(knex: Knex): Promise<void> {
  const senhaHash = await bcrypt.hash('Senha@123', 10);
  const UUID_CONDOMINIO = await knex('condominios')
    .select('uuid')
    .first()
    .then((row) => row?.uuid);

  await knex('usuarios').insert([
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SANDRA REGINA FRANÇA ABREU DE MACEDO',
      rg: '898390',
      cpf: '23321768615',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LEVINA FELIX DE FARIAS',
      rg: '01.902-17',
      cpf: '25082133415',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ZELI ISABEL AMBROS',
      rg: '12.216-50',
      cpf: '25582950044',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANTONIO DOS ANJOS CUSTODIO MAIA',
      rg: '152.808-16',
      cpf: '25806394115',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'THAIS BLAYA LEITE GREGOLIS',
      rg: '249.306-03',
      cpf: '26149799883',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RICARDO VICTOR SOUTO',
      cpf: '26252678449',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ÂNGELO MÁRCIO CALIXTO BONAMIGO',
      rg: '34.622.720-3',
      cpf: '27016562816',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARI VANESSA KAORI YOMURA PIOVEZAM',
      cpf: '27048070862',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSUE RODRIGUES DA SILVA',
      rg: '24.794-35',
      cpf: '28145445949',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALEXANDRE LUCIO AMARO',
      rg: '347.328-37',
      cpf: '28588761858',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUCIENE ROCHA',
      rg: '30.782.832-3',
      cpf: '28997970852',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RUDNEY MARCAL',
      rg: '32.733.757-8',
      cpf: '29724049809',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ADRIANO DRACHENBERG',
      rg: '27.898.329-7',
      cpf: '29851387878',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LURDIMAR GONÇALVES RESENDE',
      rg: '10.192-53',
      cpf: '30047382104',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCO JURANDIR LIMA VICTOR',
      rg: '187623',
      cpf: '30164656200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSEMIR MELO NOGUEIRA',
      rg: '01.752-42',
      cpf: '30785634215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANTONIO MARCOS CAETANO DA SILVA',
      rg: '188001',
      cpf: '30816521204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA CRISTINA SOARES ROCHA',
      rg: '171866',
      cpf: '30823439291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JORGE DIAS ANDRADE SOBRINHO',
      rg: '3264',
      cpf: '30835224287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'IRACEMA DA SILVA RIBEIRO',
      rg: '040515',
      cpf: '30858127253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DULCINÉIA VAZ DA SILVA',
      rg: '199105',
      cpf: '30875684220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'BEATRIZ HADADD FIGUEREIDO',
      cpf: '31177276801',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RICARDO RIBEIRO DE MOURA LEITE',
      rg: '338996',
      cpf: '31544829892',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ILMARA RODRIGUES LIMA VASCONCELOS',
      cpf: '32200625200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANDRE LUIZ PARIGOT',
      rg: '01.902-16',
      cpf: '32240090200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DOUGLAS SCARPIM',
      rg: '440.453-57',
      cpf: '32468307895',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'REGINALDO BISPO DE SOUZA',
      rg: '02.864-00',
      cpf: '32602553204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'TATIANE CASELLATTO ROSALEM OLIVER',
      rg: '335.522-39',
      cpf: '33243866839',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALBERTO DALACOSTA',
      rg: '12.816-45',
      cpf: '33515883991',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PEDRO NOGUEIRA TEIXEIRA DA ROCHA',
      rg: '317345',
      cpf: '33853190804',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CARLA MARIA DE SOUZA MOURÃO',
      rg: '193352',
      cpf: '33998671234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LESLIE CASTELO DE VASCONCELOS',
      rg: '166403',
      cpf: '34005625215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA LIZETE LINS LIMA',
      rg: '146764',
      cpf: '34037292220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA AURINETE LIMA DA SILVA',
      rg: '147121',
      cpf: '34037322234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EDSON GOMES BATISTA',
      rg: '359632',
      cpf: '35012684249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALZENEIDE DE CASTRO AQUINO',
      rg: '207139',
      cpf: '35058102234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EDNALDO DE SOUZA SILVA',
      rg: '367638',
      cpf: '35090359253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MAYKON RODRIGO POSSONI DA SILVA',
      rg: '38.551.580-7',
      cpf: '35154941896',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GILSON PESCADOR',
      rg: '21.844-12',
      cpf: '35481854953',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GUILHERME OLIVER',
      rg: '43.623.441-5',
      cpf: '35627658860',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CARLOS AUGUSTO DA SILVA NEGREIROS',
      rg: '1890',
      cpf: '35948060225',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EBSON JAMES DE OLIVEIRA MACEDO',
      rg: '01.891-37',
      cpf: '36034720206',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SARA SOARES DE HOLANDA',
      rg: '188793',
      cpf: '36074330204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CATERINE VASCONCELOS DE CASTRO',
      rg: '184912',
      cpf: '36085995253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOÃO PAULO ESCUDEIRO LEITE',
      rg: '12.090.361-2',
      cpf: '36526248829',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DOUGLAS JONATHAN SANTIAGO',
      rg: '13.618.648-7',
      cpf: '36673625368',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CLAUDIA MEIRY BERNARDINO DA SILVA',
      rg: '281267',
      cpf: '36711381149',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LIVIA MARIA LOPES MARTINS GODOI MARCAL',
      rg: '337.940-21',
      cpf: '37376884866',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GILBERTO LEANDRO THEON',
      rg: '10.133.255-91',
      cpf: '37603221072',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUCAS BACARIO NOGUEIRA AIELO',
      rg: '50.273.720-7',
      cpf: '38929123864',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALESSANDRO ALVES FERREIRA',
      rg: '427590',
      cpf: '39038270291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GLENN KELSON DA SILVA CASTRO',
      cpf: '39081893220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'WAGNER RAMOS LEME',
      rg: '12.020.304-57',
      cpf: '39088049220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA DO PERPETUO SOCORRO PEREIRA PONTES',
      rg: '21830',
      cpf: '39096300220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CARLOS HENRIQUE MARINHO DE ANDRADE',
      rg: '222570',
      cpf: '39141969200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA CONCEIÇÃO ANDRADE LABATE',
      rg: '50.052-12',
      cpf: '39242900834',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'HELTER DE OLIVEIRA MARTINS',
      rg: '32.350-36',
      cpf: '39412890630',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRILEI PEDRO LIMA VIANA',
      rg: '12.020.317-6',
      cpf: '41173961291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ADEILDE NASCIMENTO DE ALMEIDA',
      rg: '225519',
      cpf: '41191269272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GERSON CARLOS DE OLIVEIRA NUNES',
      rg: '224892',
      cpf: '41222342200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GLEIZER RODRIGUES DE LIMA',
      cpf: '41227271204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NILMAR DUTRA RAMOS BRANA',
      rg: '169543',
      cpf: '41286464234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CLÓVIS MONTEIRO GOMES',
      rg: '367936',
      cpf: '42226430253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EDNA MARIA PIMENTEL MORENO',
      rg: '105879',
      cpf: '42972272749',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SILVIA FERREIRA DOS SANTOS',
      rg: '236388',
      cpf: '43368840215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUZIA REGIO RODRIGUES',
      rg: '230390',
      cpf: '43370436291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ARLINDO GARCIA DE SOUZA',
      rg: '232074',
      cpf: '43391648287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ENEIDA RAGO LORENZETTI',
      rg: '213369',
      cpf: '43412971200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GLADSON CAMELI',
      rg: '00.000-12',
      cpf: '43461107204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANDREY ROBSON DA SILVA RIBEIRO',
      rg: '237897',
      cpf: '43493882220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RUYMAR BATISTA MATIAS',
      rg: '238071',
      cpf: '43499791234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'WILSON JOSE DAS CHAGAS SENA LEITE',
      rg: '282035',
      cpf: '43507018268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LAURA SIMONE NASCIMENTO RODRIGUES',
      rg: '246921',
      cpf: '43542719234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANDREA HEIDRICH THOEN',
      rg: '10.033.600-3',
      cpf: '44275196015',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALZIRA MARIA TAVARES ALENCAR',
      rg: '223899',
      cpf: '44373147272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSENEY CORDEIRO DA COSTA',
      rg: '2180',
      cpf: '44411081253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALEXANDRE BONFIM NUNES',
      rg: '323174',
      cpf: '44415400272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'AGLAILSON DE QUEIROZ ARAÚJO',
      rg: '02.769-09',
      cpf: '45963924120',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA ANDRADE SILVA',
      rg: '254924',
      cpf: '46132562249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EUSIMAR MARQUES DA LUZ FERREIRA',
      rg: '119.671-29',
      cpf: '46151850220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCO TELLES JUNIOR',
      cpf: '46158847291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'BARBARA PERDOME MACHAO NUNES',
      rg: '38.498.236-0',
      cpf: '46222943881',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SEBASTIÃO VIRGILIO OLIVEIRA FERREIRA',
      rg: '232598',
      cpf: '46545999249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VANDERCI APARECIDA DRANCHEBERG',
      rg: '47.435-10',
      cpf: '47246600825',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SILVANO CLAUDIO FELIX VASCONCELOS',
      rg: '02.397-10',
      cpf: '47774258272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALMIRA PEREIRA GONÇALVES',
      rg: '02.612-28',
      cpf: '47798645268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISLEYDE FREIRE DA COSTA DE SOUZA',
      rg: '273960',
      cpf: '47812559220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RODRIGO ALEXANDRE SANTOS DE SOUZA',
      rg: '239239',
      cpf: '48373788204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ISABEL MOURA MARQUES',
      rg: '250397',
      cpf: '48397628215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARCOS LOURENÇO BEZERRA DA SILVA',
      rg: '262535',
      cpf: '48436615204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JORCINEI WIDSON PEREIRA',
      rg: '259249',
      cpf: '48450618215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOVELINA MARIA DE MOURA',
      rg: '02.580-74',
      cpf: '48453358249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GUSTAVO DE SOUZA CALIXTO',
      cpf: '48905083846',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EVANI SANTOS DE OLIVEIA ARAUJO',
      cpf: '49005375191',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ABRAAO ELIAS ABUGOCHE P LEME',
      rg: '261436',
      cpf: '49513770206',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EDIVALDO DA SILVA FIGUEIREDO',
      rg: '12.020.343-68',
      cpf: '49522957291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VINICIUS MENANDRO EVANGELISTA DE SOUZA',
      rg: '263133',
      cpf: '49555219249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KARLA CARRIÇO FERREIRA',
      rg: '106.610-26',
      cpf: '50324135200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VANIA LUCIA MOURÃO DE BRITO',
      rg: '249077',
      cpf: '50822578204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA GORETE LIMA DE BARROS',
      rg: '02.839-08',
      cpf: '50849603234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EMERSON RAGO',
      rg: '00.232.205-6',
      cpf: '51001969200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'HENZIO DA SILVA ALBUQUERQUE',
      rg: '308105',
      cpf: '51026945291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CLEISON MAIA CARVALHO',
      rg: '270658',
      cpf: '51060906287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'WELLYNGTON MENEZES DE MELO',
      rg: '256438',
      cpf: '51081938234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'HILDO REGO RODRIGUES',
      rg: '348439',
      cpf: '51113507291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANA CAROLINE GOMES FERREIRA ROESLER',
      rg: '03.262-94',
      cpf: '51164868268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DENES BEZERRA DE CARVALHO',
      rg: '12.110.431-36',
      cpf: '51179091272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FLAVIA DE AZEVEDO COUTINHO',
      rg: '032.211-01',
      cpf: '51205696253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCO WESLEY GOMES DOS SANTOS',
      rg: '03.369-16',
      cpf: '51217295291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VINICIUS DE OLIVEIRA ARAUJO',
      rg: '332183',
      cpf: '51227886268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUCAS ANDRADE E SILVA',
      rg: '297757',
      cpf: '51247666204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SILVIO ARAUJO DA SILVA',
      rg: '3588',
      cpf: '51262983215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EDUARDO VASCONCELOS PASSOS',
      rg: '347962',
      cpf: '51576155234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SAMARA MOTA DE ARAUJO',
      rg: '320889',
      cpf: '51652366253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NATALIA PIMENTEL MORENO MANTILLA',
      rg: '311336',
      cpf: '51677563249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DANIELLE CUSTODIO ROCHA ARAUJO',
      rg: '319387',
      cpf: '51845970268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RAFAEL MAÇANEIRO DE OLIVEIRA',
      rg: '385448',
      cpf: '51855550253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSÉ HENDSON CORTEZ DE MOURA',
      rg: '12.020.310-91',
      cpf: '51861160259',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'OSMAR NILO DE JESUS LIMA BEZERRA',
      rg: '362143',
      cpf: '51878852272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ARYNE CUNHA DO NASCIMENTO',
      rg: '342840',
      cpf: '51895404215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALENE CUNHA DO NASCIMENTO',
      rg: '343518',
      cpf: '51895420253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'HANNA CHRISLENE DA ASSUNÇÃO CORREIRA E SILVA',
      rg: '433597',
      cpf: '51919494200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SILVIO FORASTIERO FRAZAO',
      rg: '10.618.603-08',
      cpf: '52156362220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCYLLENE ACASSIA DALACOSTA',
      rg: '551778',
      cpf: '52197018272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GABRYELLE PIRES MARZOLA',
      rg: '62.970.738-8',
      cpf: '52202721878',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FLAVIA ALBURQUERQUE RODRIGUES',
      rg: '346345',
      cpf: '52230589253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ELMA LARISSA NUNES DOS SANTOS FERREIRA',
      rg: '359453',
      cpf: '52263070206',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'WENISON MAGALHÃES DO NASCIMENTO',
      rg: '12.020.330-71',
      cpf: '52304965253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CHRISTIANNE SOARES ROCHA JUCÁ',
      rg: '393710',
      cpf: '52617327272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CINTHIA MICHELLI MELLO DA SILVA',
      rg: '428242',
      cpf: '52724182200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KEURI LIMA DA SILVA CANIZO',
      rg: '387232',
      cpf: '52773671287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'BRUNA ARRUDA SOARES',
      rg: '130.418-35',
      cpf: '52874206253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'TEHANI SCHNEKENBERG TELLES',
      rg: '518386',
      cpf: '52880052149',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PAULO HENRIQUE FELICIO',
      rg: '470950',
      cpf: '52945626268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'AIRTON CEZINO FELICIO',
      rg: '470949',
      cpf: '52945634287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'WESLEY CARLOS NASCIMENTO',
      rg: '100.109-47',
      cpf: '52969959291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DIANNA CARLOS NASCIMENTO BARROS',
      rg: '100.510-15',
      cpf: '52969975220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RAFAEL HADDAD FIGUEIREDO',
      cpf: '52978680253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ISMAEL LIMA DE ABREU',
      rg: '422214',
      cpf: '53065280230',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CAMILA DE HOLANDA VASCONCELOS',
      rg: '105.478-43',
      cpf: '53187660215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DAISY DE FREITAS ALMEIDA',
      cpf: '54958237453',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCO PAULO SIMAO DE OLIVEIRA',
      rg: '02.588-76',
      cpf: '55901697200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RAFAEL ROCHA PIRES BARBOZA',
      rg: '66.972.634-5',
      cpf: '57272348836',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'OSVALDO DA SILVA SOUZA',
      rg: '02.350-71',
      cpf: '57326509204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'AIEZA DOS SANTOS BANDEIRA',
      rg: '02.711-24',
      cpf: '57359911249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VANESSA CARLA DA SILVA ARAÚJO',
      rg: '256115',
      cpf: '57931925220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RENATO CORREIA DA SILVA',
      rg: '1158',
      cpf: '57995079249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSÉ NEVES RIBEIRO DA SILVA',
      rg: '12.000.293-29',
      cpf: '58231951253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RONAN ZANFORLIM BARBOSA',
      rg: '11.122-81',
      cpf: '58502769120',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ROBERTO BARROS DOS SANTOS',
      rg: '243858',
      cpf: '58854096253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RUTH SILVA LIMA DA COSTA',
      rg: '02.871-40',
      cpf: '58854215287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALBERTO DALACOSTA FILHO',
      rg: '497165',
      cpf: '59530626215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RONALDO DE FREITAS LIMA',
      rg: '12.000.298-4',
      cpf: '60266651291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARINEUSA REGINA FÉLIX DE MOURA',
      rg: '60.404.183-20',
      cpf: '60404183204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FERNANDA DE SOUZA LIMA',
      rg: '394349',
      cpf: '60693053291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LINDINALVA MESSIAS DO N CHAVES',
      cpf: '60693711787',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARCELO BADER RIBEIRO',
      rg: '264704',
      cpf: '61092762272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RENATA BIRIBA AGUIAR',
      rg: '14.087-82',
      cpf: '61144835100',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ADCARLOS DA SILVA FREITAS',
      rg: '02.986-12',
      cpf: '61438790287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PAULO ROBERTO CORREIA DA SILVA',
      rg: '27.756-86',
      cpf: '61463587268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSÉ MARIO PEREIRA DANTAS',
      rg: '281610',
      cpf: '61478385200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ORICÉLIO DA COSTA MARTINS',
      rg: '12.090.382-6',
      cpf: '61518182291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARINA ORIAR DA SILVA SANTOS',
      rg: '315873',
      cpf: '62120042268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ELIANE LEITE DA ROCHA',
      rg: '300574',
      cpf: '62501151291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA ELIZETE DE ARAUJO PEREIRA',
      rg: '315245',
      cpf: '62921258234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RONNIERE STENIO FREITAS JUCA',
      rg: '276393',
      cpf: '62936166268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SUELY NOVAIS DA SILVA',
      rg: '03.260-58',
      cpf: '62972170253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DEBORAH FERNANDA SENA DOS SANTOS',
      rg: '03.183-94',
      cpf: '63063603287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MAYDANO FERNANDES DE MIRANDO',
      rg: '313800',
      cpf: '63094916287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUIZ ROGERIO DE OLIVEIRA',
      rg: '632.232.952-91',
      cpf: '63223295291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'BRUNO DA SILVA',
      rg: '02.950-21',
      cpf: '63790220230',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARA RUBIA OLIVEIRA',
      rg: '286164',
      cpf: '63805162200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ROSANGELA MARIA NOVAIS DA SILVA',
      rg: '561722',
      cpf: '63921146291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NADIR DE SOUZA BONI',
      rg: '309605',
      cpf: '64164195215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RENATA BELTRÃO TEIXEIRA YOMURA',
      rg: '970.023.329-09',
      cpf: '64317900300',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DULCILEIDE R. DE M. DALACOSTA',
      rg: '109.801-72',
      cpf: '64602605249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'AKERNA CRISTINI DE MOURA PEREIRA',
      rg: '03.092-83',
      cpf: '64737314234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUIZ AUGUSTO HADDAD FIGUEIREDO',
      rg: '199089',
      cpf: '64937194291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CARLOS LOPES DO PRADO JUNIOR',
      rg: '117.780-59',
      cpf: '65014391168',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA ROSANGELA DO NASCIMENTO VIEIRA',
      rg: '439358',
      cpf: '65133250215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'BIANKA DA COSTA CARDOSO',
      rg: '300242',
      cpf: '65214943253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EDILCLECIA PEREIRA GOMES DE ARAUJO',
      rg: '03.147-25',
      cpf: '65426584249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'HUDSON KLEY SILVA DE OLIVEIRA',
      rg: '12.020.305-22',
      cpf: '65532813272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KAREN MESQUITA DA SILVA TEIXEIRA DA ROCHA',
      rg: '288822',
      cpf: '65543228215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ELINETE DE SOUZA FROTA BOMFIM',
      rg: '03.380-10',
      cpf: '65837401253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCO EDEVALDO SANTIAGO DE MENDONÇA',
      rg: '12.090.363-6',
      cpf: '66451841234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KATIUZA F. DALACOSTA DE MELO',
      rg: '538231',
      cpf: '66464765272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANDERSON DA SILVA RIBEIRO',
      rg: '02.851-81',
      cpf: '66692253268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'IRINEIA BARBOSA GOMES AIELO',
      rg: '03.307-22',
      cpf: '66694078234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SULAMITA NOVAIS DA SILVA',
      rg: '346997',
      cpf: '66726212291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LAURA MARIA CARDOSO',
      rg: '00.103.606-6',
      cpf: '67001300853',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANTONIO VALNEI VIANA DE MENDONÇA',
      rg: '228111',
      cpf: '67246427287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SIMONE JAQUES DE AZAMBUJA SANTIAGO',
      cpf: '67481221049',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUIZ CARLOS SIQUEIRA DA SILVA',
      rg: '12.090.370-26',
      cpf: '67667465215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARQUELO SILVA DE JESUS',
      rg: '12.090.373-23',
      cpf: '67833039268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GUIDO WAGNER VILHAMOR JUNIOR',
      rg: '02.707-84',
      cpf: '68238266220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KELLEY JANINE FERREIRA DE OLIVEIRA',
      rg: '133.090-07',
      cpf: '68245351253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NEIVA MARIA NASCIMENTO DA CONCEIÇÃO',
      rg: '105.508-52',
      cpf: '68305770206',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PELEGRINA BARROS DA SILVA MOREIRA',
      rg: '338289',
      cpf: '68308035272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'THIAGO NOGUEIRA TEIXERA DA ROCHA',
      rg: '03.173-43',
      cpf: '68697201268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANTONIO WILLIAN VIELA VIANA',
      rg: '69.012-49',
      cpf: '68697988500',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RAFAEL ANTONIO LORENZETTI',
      rg: '393.100-60',
      cpf: '68717121272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DOGELCE NEVES VIEIRA JUNIOR',
      cpf: '68842600172',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOÃO TERRA NETTO PEREIRA',
      rg: '690048',
      cpf: '68949979268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GISELDA MOREIRA COSTA SCHARNOSKI',
      rg: '290483',
      cpf: '68999621039',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSE RICARDO SIQUEIRA SILVA JUNIOR',
      rg: '102.535-72',
      cpf: '69000697115',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LEO GONZAGA DE SOUZA FERREIRA',
      rg: '233553',
      cpf: '69026599234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUIZ AUGUSTO MATOS DA SILVA',
      rg: '370041',
      cpf: '69105413249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA IRENE SILVA DOS SANTOS',
      rg: '226808',
      cpf: '69107084234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RODRIGO RIBEIRO MOURA LEITE',
      rg: '36.718.527-1',
      cpf: '69258031253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ADALBERTO CORDEIRO DE SOUZA',
      rg: '3361',
      cpf: '69399662268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'IZAUL LUNA SILVERIO',
      rg: '3239',
      cpf: '69403813253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GUSTAVO PONTES MARQUES DA SILVA',
      cpf: '69450439168',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DALTON GOMES DA SILVA',
      rg: '368905',
      cpf: '69476918268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JAIRTON FERREIRA SILVÉRIO',
      rg: '374449',
      cpf: '69489661287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JAQUELINE GOMES DA ROCHA',
      rg: '12.090.392-20',
      cpf: '69599696204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ELISANGELA ALVES DE LIMA',
      rg: '374441',
      cpf: '69655090230',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARLON RODRIGUES DA SILVA',
      rg: '290747',
      cpf: '70015236234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ELIZÂNGELA MARIA DE CARVALHO PAIXÃO',
      rg: '356374',
      cpf: '70189412291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FLORIAN BONNIN',
      rg: '17.102-65',
      cpf: '70529327171',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ELSON DA COSTA LIMA',
      rg: '12.020.319-34',
      cpf: '70969450249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GABRIEL SILVA DA COSTA',
      rg: '334073',
      cpf: '70975329200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA ANTONIA CAMILO DA SILVA',
      rg: '386924',
      cpf: '70995362220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NORMA GIOVANNA DA SILVA PEREIRA PLESE',
      rg: '03.379-96',
      cpf: '71005994284',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VALERIA LIMA DE MESQUITA',
      rg: '03.365-19',
      cpf: '71280774215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JUSSARA GONÇALVES FERNANDES RODRGIUES',
      rg: '129.862-16',
      cpf: '71287540244',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GIOVANA MARIA DE SOUZA BONI',
      rg: '355698',
      cpf: '71547819200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANDRÉ DA SILVA SANTOS',
      cpf: '71923284215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JAMARA MAIA BARROS',
      rg: '393335',
      cpf: '71941592287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LILIANE DA FONSECA LIMA',
      rg: '03.349-64',
      cpf: '71947701215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FREDERICO ARAUJO GALLO',
      rg: '94.014.006-07',
      cpf: '72348976315',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RIVADALVE COELHO GONÇALVES',
      rg: '56.407-06',
      cpf: '72398426653',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KATIUSCIA DE LIMA MENDONÇA',
      rg: '115.467-43',
      cpf: '72660333220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'THIAGO LUCENA DE PAULA AFONSO',
      rg: '391582',
      cpf: '73000175253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LISSANDRA BARCELAR FREITAS',
      rg: '08.461.726-82',
      cpf: '73417300568',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JEFFERSON SANTANA DE MENESES',
      rg: '12.110.428-73',
      cpf: '73517666220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JEFFERSON PEREIRA DA SILVA',
      rg: '12.090.367-55',
      cpf: '73682373268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALVARO MIGUEL ROCHA SOLER',
      rg: '286589',
      cpf: '73713813272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCA MEIRE SANTOS DA SILVA',
      rg: '73.732.044-22',
      cpf: '73732044220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RODOLFO TELLES DE PAIVA',
      rg: '365295',
      cpf: '73766100220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CLISINEIDE LIMA GOMES DE SOUZA',
      rg: '333736',
      cpf: '73943096220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARCEL FERRARI LONGUINI',
      rg: '370191',
      cpf: '74066390234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARCELA BADER RIBEIRO',
      rg: '340582',
      cpf: '74094297200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSIALDO APARECIDO BATISTA FERREIRA',
      rg: '400037',
      cpf: '74210343234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'TEOTONIO RODRIGUES SOARES JUNIOR',
      rg: '741578',
      cpf: '74232533249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RODRIGO ROESLER',
      rg: '12.962-53',
      cpf: '74354329034',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANA PAULA NASCIMENTO VIDAL',
      rg: '411037',
      cpf: '74965190220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CARLOS AUGUSTO DA COSTA PESCADOR',
      rg: '295973',
      cpf: '75173514272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSE THIAGO HOLANDA DA CONCEIÇAO',
      rg: '396230',
      cpf: '75195933200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ROBERTO DA SILVA RIBEIRO',
      rg: '12.090.396-34',
      cpf: '75222310272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ARETHA DE ABREU SARKIS',
      rg: '378045',
      cpf: '75411482291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LAIS BITTENCOURT PIRES MATOS DA SILVA',
      rg: '410848',
      cpf: '75567318200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FERNANDO AMBROS RIBEIRO',
      rg: '40.788.011-17',
      cpf: '75945887287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MAGNO SILVA DE OLIVEIRA',
      rg: '12.090.407-80',
      cpf: '76662071234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUCIANA ANDRE DOS SANTOS MAIA',
      cpf: '76815099415',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSE DOS SANTOS JUNIOR',
      rg: '346354',
      cpf: '77013131253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSE JAIR CAVALCANTE DE FIGUEIREDO',
      cpf: '77111435249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'HARON DA CUNHA CORREIA',
      rg: '303797',
      cpf: '77210310282',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PAULO HENRIQUE DE O FERNANDES VALE',
      rg: '410496',
      cpf: '77352378200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALAN DA SILVA SANTOS',
      rg: '347005',
      cpf: '77600398249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALINE GADELHA MAIA',
      rg: '22.546.305-98',
      cpf: '77846818287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'BRUNO SAMUEL PEREIRA GOMES SILVA',
      rg: '286981',
      cpf: '78253594291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'REINALDO SANTOS MORAIS NETO',
      rg: '57.627-80',
      cpf: '78308208215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ISNARD HENRI DE ALMEIDA PIRES',
      rg: '380205',
      cpf: '78379989287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSE DONIZETI AIELO',
      rg: '81.270-06',
      cpf: '78438616887',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JULIANA MARQUES DE LIMA FARIA',
      rg: '20.924-62',
      cpf: '78572819134',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ÍTALA MARIA DE OLIVEIRA FERREIRA DE PAULA AFONSO',
      rg: '384366',
      cpf: '78636990297',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FÁTIMA GISLANE LIMA SILVA AIELO',
      rg: '759.685-14',
      cpf: '78643139815',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FELIPE NEGREIROS DE BARROS',
      rg: '132.005-34',
      cpf: '78662028268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CLAUDEMIRA RODRIGUES DE ANDRADE MOTA',
      rg: '402413',
      cpf: '78712661287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PAULO CESAR BARATO DOS SANTOS',
      rg: '415038',
      cpf: '79258506200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'OCYRLEI SOUZA DA SILVA',
      rg: '12.090.380-90',
      cpf: '79400388268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'BAIRO GUEDES COSTA',
      rg: '12.090.370-92',
      cpf: '79708803200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'THYAGO RODRIGUES LAMEIRA',
      rg: '03.262-21',
      cpf: '80232655200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CLÁUDIO ROMMERO DA SILVA BATISTA',
      rg: '446506',
      cpf: '80240518268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GALBER PORTELA DA COSTA ALMEIDA',
      rg: '348052',
      cpf: '80288430263',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LARISSA LEITE DE CARVALHO',
      rg: '458165',
      cpf: '80312187220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'TALITA GONÇALVES VIEIRA GOMES',
      rg: '306677',
      cpf: '80730175300',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'THIAGO GONÇALVES VIEIRA',
      rg: '307509',
      cpf: '80730191249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SUELLEN DA COSTA VIEIRA SOLER',
      rg: '313614',
      cpf: '80863655220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOELTON DE ALMEIDA COSTA',
      rg: '14.894-32',
      cpf: '80958435120',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'WAGNER EUFRAZIO DA SILVA',
      rg: '422295',
      cpf: '81032153253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ITALO MAIA VIEIRA',
      rg: '405735',
      cpf: '81163401234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARILENE MENEZES PINTO',
      rg: '336040',
      cpf: '81313586234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCO MÁRCIO MEDEIROS ROSEMIR',
      rg: '00.121.712-0',
      cpf: '81355483468',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA ELIZA SCHETTINI CAMPOS HIDALGO VIANA',
      rg: '429448',
      cpf: '81500254991',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JADE DENE',
      rg: '419.757-31',
      cpf: '81532083068',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ERLANDE FEITOSA DOS SANTOS',
      rg: '353518',
      cpf: '81741227291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOANNA NATALIA FARIAS B. RESENDE',
      rg: '428098',
      cpf: '82328625215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JADSON HENRIQUE ARAUJO DA SILVA',
      rg: '12.090.363-75',
      cpf: '82398747204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'BENEDITO CÉLIO MARINHO DO NASCIMENTO',
      rg: '3684',
      cpf: '82409625215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GILBERTO MATOS DE ARAUO',
      rg: '10.018-37',
      cpf: '82679061187',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'IZAMIDE MACIEL GRANGEIRO',
      rg: '293351',
      cpf: '82960410220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FRANCISCO AFONSO CHAVES DE LIMA JUNIOR',
      rg: '12.090.407-4',
      cpf: '83026959200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GLENDA LIMA DE ABREU',
      rg: '447402',
      cpf: '83121005200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NAIANA NATACHA SOUZA CARVALHO GONÇALVES',
      rg: '413508',
      cpf: '83189823200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PATRICIA MELO GANUM',
      rg: '455551',
      cpf: '83706135272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JAIR ONOFRE DE ANDREADEE SILVA NETO',
      rg: '12.110.424-77',
      cpf: '83834290297',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANA CAROLINY MANSOUR RIBEIRO DO VALLE',
      rg: '100.018-83',
      cpf: '83878416253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUANA MARIA NUNES DOS SANTOS TEIXEIRA',
      rg: '458721',
      cpf: '83886109291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CATARINA DE SOUZA COSTA',
      rg: '430617',
      cpf: '83973702268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VANESSA CANDINI SILVA OLIVEIRA FERREIRA',
      rg: '411007',
      cpf: '84043350104',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'HELTON SOARES TELES',
      rg: '418226',
      cpf: '84258438200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RAYANY ANDRADE MARTINS',
      cpf: '85102202200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CLEIDSON BURJACK DINIZ',
      rg: '111.807-14',
      cpf: '85388106187',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ROBERTO RIBEIRO DE MOURA LEITE',
      rg: '409144',
      cpf: '85529214215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'HERIKA FERNANDA MONTILHA STRAPA',
      rg: '462542',
      cpf: '85617687204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANTONIO MAURICIO DE MATOS GONÇALVES',
      rg: '909476',
      cpf: '85908533149',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SYNARA ALLANA MOTA',
      rg: '100.632-69',
      cpf: '85958433253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ISMAYLE LIMA DE ABREU',
      rg: '423365',
      cpf: '86076035234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CLICIA COSTA DA SILVA',
      rg: '426992',
      cpf: '86408526268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANGÉLICA LIMA DE ALBUQUERQUE',
      rg: '105.739-25',
      cpf: '87283468234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CARINA LOPES TIBURCIO AMARAL GURGEL',
      cpf: '87562049220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JAMILLE BESTENE LINS TEIXEIRA DA ROCHA',
      rg: '387359',
      cpf: '88337182220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'GELSON GONÇALVES NETO',
      rg: '307523',
      cpf: '88396843287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DANIEL DOS SANTOS SOARES',
      rg: '363455',
      cpf: '88404250200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JORGE MIRANDA RODRIGUES DE SOUZA',
      rg: '12.090.372-74',
      cpf: '88489167249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JESSICA DA CUNHA RAMOS',
      rg: '101.524-74',
      cpf: '88556930263',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JUSCELINO DA SILVA DOS SANTOS',
      rg: '035.418.560-48',
      cpf: '88577317234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARINA DE ANGELIS CARVALHO DRACHENBERG',
      rg: '135.787-23',
      cpf: '89059646215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'THAYANA LOUREIRO ARAUJO FEITOSA',
      rg: '102.149-68',
      cpf: '89315952200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'OTAVIO OLIVER',
      cpf: '89977874891',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LUCIANA LOPES RODRIGUES GONÇALVES',
      rg: '47.883-28',
      cpf: '90172590604',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'EMMIRLAY ALVES DA COSTA',
      rg: '100.592-45',
      cpf: '90296028215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIANE ROBERTA LINHARES DIAS',
      rg: '990.104.499-48',
      cpf: '90406044368',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ARTHUR DE OLIVEIRA VIANA NETO',
      rg: '564.541-87',
      cpf: '90406176949',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JEAN CARLOS BONAZONI DE SOUSA',
      rg: '129.963-94',
      cpf: '90467132291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALESSANDRE GOMES DE LIMA',
      rg: '393160',
      cpf: '90798147253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'NUBIA WELANY FARIAS DO NASCIMENTO',
      rg: '458696',
      cpf: '90843789204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RAFAEL MORAIS GONÇALVES FONSECA',
      rg: '111.679-71',
      cpf: '91152860291',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JULIANA CAJA DA SILVA',
      rg: '116.247-60',
      cpf: '91452384215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOAO VICTOR DA COSTA MACHADO',
      rg: '112.513-79',
      cpf: '91590108272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARCOS VINICIUS DA COSTA MACHADO',
      rg: '116.114-05',
      cpf: '91590132220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ELIANA RODRIGUES DOS SANTOS TRINDADE',
      rg: '101.605-15',
      cpf: '91869471253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ELIANE FREIRE BRAÑA',
      rg: '106.943-58',
      cpf: '92099602204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ROMULLO DA SILVA NOLASCO',
      rg: '468150',
      cpf: '92253989215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANTONIO TIAGO DE MENDONÇA DOS SANTOS',
      rg: '439939',
      cpf: '92281788253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ADRIANA DE OLIVEIRA MARINHO',
      cpf: '92378714149',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'TIAGO HILÁRIO DA SILVA LOPES',
      rg: '399313',
      cpf: '93089562200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DANIELE CRISTINA LORENZETTI',
      rg: '31.823-02',
      cpf: '93339372934',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'PABLO CHAVES VILHAMOR',
      rg: '431533',
      cpf: '93343329215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'THIAGO MARINHO DE ANDRADE',
      rg: '933.656.672-53',
      cpf: '93365667253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANA SARA PACÍFICO CRUZ',
      rg: '455364',
      cpf: '93796439268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'FELIPE MONTEIRO BRANA',
      rg: '12.090.388-34',
      cpf: '93820429204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RAFAEL DE CARVALHO TEIXEIRA',
      rg: '428568',
      cpf: '93829302215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANNAYARA VIDAL DE SA',
      rg: '103.129-86',
      cpf: '93949634215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA ALESSANDRA MARIA NO LEITE',
      rg: '940.460.422-49',
      cpf: '94046042249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RENER VALLE DE QUEIROZ',
      rg: '444627',
      cpf: '94270519287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANNIELLY DA SILVA FERREIRA GOMES',
      rg: '104079',
      cpf: '94320845234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DIEGO CASTRO DE MELO',
      rg: '346507',
      cpf: '94659710220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ADRIANA KARIM DE ARAUJO NOGUEIRA',
      rg: '101.587-23',
      cpf: '94907056249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'DANIELE SILVA COSTA',
      rg: '104.661-18',
      cpf: '95330658268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VINICIUS FERNANDO DE CASTILHOS GOMES',
      rg: '10.551-47',
      cpf: '95764410215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'RODRIGO BRAGA DE MELO',
      rg: '103.263-24',
      cpf: '95999892287',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SERGIANE AMARAL GADELHA',
      rg: '113.876-10',
      cpf: '96010819253',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SABRINA DE SOUZA MOURAO',
      cpf: '96409916272',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KEVIN DE SOUZA MOURÃO',
      cpf: '96411341249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOISSE MARA DE ANDRADE',
      rg: '313141',
      cpf: '96505915168',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'MARIA ALDENIRA FERNANDES DA SILVA',
      rg: '326130',
      cpf: '96773570263',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'SAMIA ALMEIDA MATOS',
      rg: '12.140.473-4',
      cpf: '96783257215',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    // {
    //   uuid: uuidv4(),
    //   uuid_condominio: UUID_CONDOMINIO,
    //   nome: 'SILVESTER THAYLLON FREITAS ALVES',
    //   rg: '12.090.396-68',
    //   cpf: '96783257215',
    //   senha: senhaHash,
    //   perfil: 'morador',
    //   created_by: 'seed',
    //   updated_by: 'seed',
    // },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CATERINI DA SILVA SOUZA MACEDO',
      rg: '103.818-48',
      cpf: '97324876234',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ADRIELLY DE OLIVEIRA SANTOS',
      rg: '113.481-00',
      cpf: '97623490249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'LEDIANE LOPES VAZ',
      rg: '446410',
      cpf: '97832820268',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'KEITIANE DE ARAUJO MENEZES',
      rg: '12.140.472-68',
      cpf: '97835676249',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANTONIO GEVANDI RODRIGUES BARBOSA',
      rg: '12.140.460-12',
      cpf: '97962040297',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOÃO RICARDO FERREIRA DA SILVA',
      rg: '102.792-88',
      cpf: '98120190220',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'VALDEMIR BARBOSA DOS SANTOS JUNIOR',
      rg: '408669',
      cpf: '98215507204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JACKELINE FRANÇA DE LIMA',
      rg: '106.865-68',
      cpf: '98491300244',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JOSÉ DIONES MELEIRO GOMES',
      rg: '106.565-02',
      cpf: '98677128204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALINE MEIER MURARO DE MATOS',
      rg: '11.841-21',
      cpf: '98699687168',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'CIRO JÔNATAS DE SOUZA OLIVEIRA',
      rg: '458732',
      cpf: '98837770278',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ANDRESSA DA SILVA FREITAS',
      rg: '101.608-68',
      cpf: '98892878204',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'ALICE PESSOA LESSA',
      rg: '107.687-00',
      cpf: '99574071200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
    {
      uuid: uuidv4(),
      uuid_condominio: UUID_CONDOMINIO,
      nome: 'JACINTA SALES DA COSTA',
      rg: '107.298-44',
      cpf: '99648458200',
      senha: senhaHash,
      perfil: 'morador',
      created_by: 'seed',
      updated_by: 'seed',
    },
  ]);
}
