import type { Knex } from 'knex';
import * as bcrypt from 'bcrypt';

const UUID_CONDOMINIO_INICIAL = '11111111-1111-4111-8111-111111111111';

export async function seed(knex: Knex): Promise<void> {
  const senhaHash = await bcrypt.hash('Senha@123', 10);

  await knex('usuarios').del();

  await knex('usuarios').insert([
    {
      uuid: '11111111-1111-4111-8111-111111111111',
      uuid_condominio: UUID_CONDOMINIO_INICIAL,
      nome: 'Haron Correia',
      email: 'haroncorreia@hotmail.com',
      celular: '11990000001',
      senha: senhaHash,
      perfil: 'super',
      activation_code_hash: null,
      activation_code_exp: null,
      activated_at: knex.fn.now(),
      reset_password_token_hash: null,
      reset_password_exp: null,
      refresh_token_hash: null,
      refresh_token_exp: null,
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: '22222222-2222-4222-8222-222222222222',
      uuid_condominio: UUID_CONDOMINIO_INICIAL,
      nome: 'Usuário Admin',
      email: 'admin@recantoverdeac.com.br',
      celular: '11990000002',
      senha: senhaHash,
      perfil: 'admin',
      activation_code_hash: null,
      activation_code_exp: null,
      activated_at: knex.fn.now(),
      reset_password_token_hash: null,
      reset_password_exp: null,
      refresh_token_hash: null,
      refresh_token_exp: null,
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: '33333333-3333-4333-8333-333333333333',
      uuid_condominio: UUID_CONDOMINIO_INICIAL,
      nome: 'Usuário Portaria',
      email: 'portaria@recantoverdeac.com.br',
      celular: '11990000003',
      senha: senhaHash,
      perfil: 'portaria',
      activation_code_hash: null,
      activation_code_exp: null,
      activated_at: knex.fn.now(),
      reset_password_token_hash: null,
      reset_password_exp: null,
      refresh_token_hash: null,
      refresh_token_exp: null,
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
    {
      uuid: '44444444-4444-4444-8444-444444444444',
      uuid_condominio: UUID_CONDOMINIO_INICIAL,
      nome: 'Usuário Morador',
      email: 'morador@recantoverdeac.com.br',
      celular: '11990000004',
      senha: senhaHash,
      perfil: 'morador',
      activation_code_hash: null,
      activation_code_exp: null,
      activated_at: knex.fn.now(),
      reset_password_token_hash: null,
      reset_password_exp: null,
      refresh_token_hash: null,
      refresh_token_exp: null,
      created_by: 'seed',
      updated_by: 'seed',
      deleted_at: null,
      deleted_by: null,
    },
  ]);
}
